entity: add new entity-listener tag
axelor/axelor-open-platform pull request #25
Opened 2018-04-09 06:21 UTC by beuss

Allow entities to declare listeners that'll be invoked during lifecycle.
This allows to perform consistency checks in a more reliable way than
overriding repository save() method as listeners are called even in case
of cascading persist.
Annotation has been modified to allow avoiding imports since for
@EntityListeners we need to pass .class which doesn't play well with
autoimport. Alternative would have been to import and append '.class' to
annotation param by the mean of another boolean parameter.

2018-04-11 07:42 UTC, axeloradmin commented
We already have plan for this feature. However, it was not implemented because of one limitation of listeners (we can't use entity manager inside them). Still it can be useful for pure computation/validation. We'll consider it for next 5.1 or 5.2 release.

BTW, would you please sign the [CLA](https://github.com/axelor/axelor-development-kit/blob/master/CONTRIBUTING.md#contributor-license-agreement)?

2018-04-11 07:44 UTC, beuss commented
Hi,
Yes, the limitation is quite annoying but as you said, it can still be useful for basic consistency checks.
The CLA has been signed and sent long time ago (25/10/2017) and sent to info@axelor.com as requested
Regards

2018-12-04 15:14 UTC, axeloradmin commented
Would you please rebase this patch on dev branch? We'll integrate it in 5.1 release.

2018-12-04 16:41 UTC, beuss commented
@axeloradmin Done :-)

2018-12-05 10:09 UTC, axeloradmin requested changes
See the comments and make the changes accordingly.

2018-12-05 10:09 UTC, axeloradmin commented on axelor-core/src/main/resources/domain-models.xsd
> +      <xsd:element name="entity-listener" type="dm:EntityListener" minOccurs="0" maxOccurs="unbounded">
This should be last element not first.

2018-12-05 10:09 UTC, axeloradmin commented on axelor-core/src/main/resources/domain-models.xsd
> +    <xsd:attribute name="listenerClass" use="required">
I think better using `class` as attribute name here.

2018-12-05 10:09 UTC, axeloradmin commented on axelor-gradle/src/main/groovy/com/axelor/tools/x2j/pojo/Annotation.groovy
> -
Remove white space changes

2018-12-05 10:09 UTC, axeloradmin commented on axelor-gradle/src/main/groovy/com/axelor/tools/x2j/pojo/Annotation.groovy
> +	Annotation add(String param, List<?> values, boolean quote, boolean unwrapSingle, boolean importTypes) {
We don't need these changes. I will show you how to do that :)

2018-12-05 10:09 UTC, axeloradmin commented on axelor-gradle/src/main/groovy/com/axelor/tools/x2j/pojo/Entity.groovy
> +				listeners += it.'@listenerClass'.text() + '.class'
Change it to `listeners += it.'@class'.text()`

2018-12-05 10:09 UTC, axeloradmin commented on axelor-gradle/src/main/groovy/com/axelor/tools/x2j/pojo/Entity.groovy
> +		return new Annotation(this, "javax.persistence.EntityListeners")
Replace with following:

```
return new Annotation(this, "javax.persistence.EntityListeners")
          .add("{  ${ listeners.collect { importType(it) + '.class' }.join(', ') }}", false)
```

2018-12-11 09:54 UTC, beuss commented
@axelor all requesdt changes have been taken into account

2019-01-03 12:01 UTC, axeloradmin commented
Would you please make the required change `listeners += it.'@class'.text()` and amend the commit? We are planing to merge this for 5.1.0 soon.

2019-01-03 12:06 UTC, beuss commented
> Would you please make the required change `listeners += it.'@class'.text()` and amend the commit? We are planing to merge this for 5.1.0 soon.

Hi

Can't see what you're talking about, for me all changes (including the `listenerClass` to `class` rename) have been applied. Can you be more specific? (sorry if it's obvious)

Regards

2019-01-25 12:56 UTC, axeloradmin commented
Change line 209 to `listeners += it.'@class'.text()`. There is no need to append `.class`.

2019-01-30 15:29 UTC, beuss commented
> Change line 209 to `listeners += it.'@class'.text()`. There is no need to append `.class`.

Done

2019-01-31 14:11 UTC, axeloradmin commented
The patch is cherry picked and amended with few changes. It's now included in dev branch. Thanks!

2019-01-31 14:11 UTC, closed without merging